"""Vocabulário base do JLPT N5, organizado em tópicos progressivos."""

NIVEL = {
    "codigo": "N5",
    "nome": "Iniciante",
    "descricao": "Compreensão de japonês básico — frases simples do dia a dia, ~800 palavras.",
    "ordem": 1,
}

TOPICOS = [
    {
        "slug": "saudacoes",
        "titulo": "Saudações e expressões básicas",
        "descricao": "As primeiras palavras a aprender — usadas todo dia.",
        "palavras": [
            ("おはようございます", "おはようございます", "ohayou gozaimasu", "Bom dia (formal)", "expressão", "おはようございます、田中さん。", "Bom dia, Sr. Tanaka.", None),
            ("こんにちは", "こんにちは", "konnichiwa", "Olá / Boa tarde", "expressão", "こんにちは、元気ですか。", "Olá, tudo bem?", "Usado durante o dia."),
            ("こんばんは", "こんばんは", "konbanwa", "Boa noite (saudação)", "expressão", "こんばんは。", "Boa noite.", "Saudação ao chegar à noite."),
            ("おやすみなさい", "おやすみなさい", "oyasumi nasai", "Boa noite (ao dormir)", "expressão", "おやすみなさい。", "Boa noite (vou dormir).", None),
            ("さようなら", "さようなら", "sayounara", "Adeus / Até logo", "expressão", "さようなら、また明日。", "Tchau, até amanhã.", None),
            ("ありがとうございます", "ありがとうございます", "arigatou gozaimasu", "Muito obrigado(a)", "expressão", "本当にありがとうございます。", "Muito obrigado mesmo.", None),
            ("すみません", "すみません", "sumimasen", "Com licença / Desculpe", "expressão", "すみません、水をください。", "Com licença, água por favor.", "Serve para pedir desculpas ou chamar atenção."),
            ("ごめんなさい", "ごめんなさい", "gomen nasai", "Desculpe (sinceramente)", "expressão", "遅れてごめんなさい。", "Desculpe pelo atraso.", None),
            ("はい", "はい", "hai", "Sim", "interjeição", "はい、わかりました。", "Sim, entendi.", None),
            ("いいえ", "いいえ", "iie", "Não", "interjeição", "いいえ、違います。", "Não, está errado.", None),
            ("はじめまして", "はじめまして", "hajimemashite", "Muito prazer", "expressão", "はじめまして、ルーカスです。", "Muito prazer, sou Lucas.", "Usado na primeira vez que se encontra alguém."),
            ("よろしくおねがいします", "よろしくおねがいします", "yoroshiku onegaishimasu", "Por favor / Conto com você", "expressão", "どうぞよろしくお願いします。", "Por favor, conto com você.", "Encerra apresentações."),
        ],
    },
    {
        "slug": "pronomes-pessoas",
        "titulo": "Pronomes e pessoas",
        "descricao": "Como se referir a si mesmo e a outras pessoas.",
        "palavras": [
            ("私", "わたし", "watashi", "Eu", "pronome", "私は学生です。", "Eu sou estudante.", "Neutro, formal."),
            ("あなた", "あなた", "anata", "Você", "pronome", "あなたは日本人ですか。", "Você é japonês?", "Evite com superiores — prefira o nome."),
            ("彼", "かれ", "kare", "Ele / Namorado", "pronome", "彼は先生です。", "Ele é professor.", None),
            ("彼女", "かのじょ", "kanojo", "Ela / Namorada", "pronome", "彼女は医者です。", "Ela é médica.", None),
            ("人", "ひと", "hito", "Pessoa", "substantivo", "あの人は誰ですか。", "Quem é aquela pessoa?", None),
            ("男", "おとこ", "otoko", "Homem", "substantivo", "男の人がいます。", "Há um homem.", None),
            ("女", "おんな", "onna", "Mulher", "substantivo", "女の人がいます。", "Há uma mulher.", None),
            ("子供", "こども", "kodomo", "Criança", "substantivo", "子供が三人います。", "Há três crianças.", None),
            ("友達", "ともだち", "tomodachi", "Amigo(a)", "substantivo", "友達と遊びます。", "Vou brincar com amigos.", None),
            ("先生", "せんせい", "sensei", "Professor(a)", "substantivo", "先生はやさしいです。", "O professor é gentil.", "Também médico, mestre."),
            ("学生", "がくせい", "gakusei", "Estudante", "substantivo", "私は大学生です。", "Sou universitário.", None),
            ("名前", "なまえ", "namae", "Nome", "substantivo", "お名前は何ですか。", "Qual é seu nome?", None),
        ],
    },
    {
        "slug": "numeros-1-10",
        "titulo": "Números 1 a 10",
        "descricao": "Base de toda contagem em japonês.",
        "palavras": [
            ("一", "いち", "ichi", "Um (1)", "número", "りんごが一つあります。", "Há uma maçã.", None),
            ("二", "に", "ni", "Dois (2)", "número", "二時です。", "São duas horas.", None),
            ("三", "さん", "san", "Três (3)", "número", "三人来ました。", "Vieram três pessoas.", None),
            ("四", "よん／し", "yon / shi", "Quatro (4)", "número", "四時に会います。", "Nos vemos às quatro.", "'shi' soa como morte — 'yon' é mais comum."),
            ("五", "ご", "go", "Cinco (5)", "número", "五分待ってください。", "Espere cinco minutos.", None),
            ("六", "ろく", "roku", "Seis (6)", "número", "六時に起きます。", "Acordo às seis.", None),
            ("七", "なな／しち", "nana / shichi", "Sete (7)", "número", "七時です。", "São sete horas.", None),
            ("八", "はち", "hachi", "Oito (8)", "número", "八月です。", "É agosto.", None),
            ("九", "きゅう／く", "kyuu / ku", "Nove (9)", "número", "九時に寝ます。", "Durmo às nove.", None),
            ("十", "じゅう", "juu", "Dez (10)", "número", "十人います。", "Há dez pessoas.", None),
            ("零", "れい／ゼロ", "rei / zero", "Zero (0)", "número", "零度です。", "Está zero grau.", None),
        ],
    },
    {
        "slug": "numeros-grandes",
        "titulo": "Números maiores e contadores",
        "descricao": "Dezenas, centenas, milhares e contadores comuns.",
        "palavras": [
            ("百", "ひゃく", "hyaku", "Cem (100)", "número", "百円です。", "São 100 ienes.", None),
            ("千", "せん", "sen", "Mil (1000)", "número", "千円です。", "São 1000 ienes.", None),
            ("万", "まん", "man", "Dez mil (10000)", "número", "一万円です。", "São 10.000 ienes.", "Japonês conta em unidades de 10.000."),
            ("円", "えん", "en", "Iene (moeda)", "substantivo", "三百円です。", "São 300 ienes.", None),
            ("〜つ", "〜つ", "~tsu", "Contador genérico (1-10)", "contador", "りんごを二つください。", "Duas maçãs, por favor.", "Hitotsu, futatsu, mittsu..."),
            ("〜人", "〜にん", "~nin", "Contador de pessoas", "contador", "三人います。", "Há três pessoas.", "Exceções: hitori (1), futari (2)."),
            ("〜本", "〜ほん", "~hon", "Contador de objetos longos", "contador", "ペンを二本買いました。", "Comprei duas canetas.", "Garrafas, lápis, guarda-chuvas."),
            ("〜枚", "〜まい", "~mai", "Contador de objetos finos", "contador", "切手を三枚ください。", "Três selos, por favor.", "Papéis, camisas, pratos."),
            ("〜個", "〜こ", "~ko", "Contador de objetos pequenos", "contador", "りんごを五個ください。", "Cinco maçãs, por favor.", None),
            ("〜冊", "〜さつ", "~satsu", "Contador de livros", "contador", "本を二冊買いました。", "Comprei dois livros.", None),
            ("〜回", "〜かい", "~kai", "Contador de vezes", "contador", "三回行きました。", "Fui três vezes.", None),
        ],
    },
    {
        "slug": "dias-semana",
        "titulo": "Dias da semana",
        "descricao": "Cada dia tem um kanji ligado a um elemento natural.",
        "palavras": [
            ("月曜日", "げつようび", "getsuyoubi", "Segunda-feira", "substantivo", "月曜日は忙しいです。", "Segunda é cheia.", "月 = lua."),
            ("火曜日", "かようび", "kayoubi", "Terça-feira", "substantivo", "火曜日に会います。", "Nos vemos na terça.", "火 = fogo."),
            ("水曜日", "すいようび", "suiyoubi", "Quarta-feira", "substantivo", "水曜日は休みです。", "Quarta é folga.", "水 = água."),
            ("木曜日", "もくようび", "mokuyoubi", "Quinta-feira", "substantivo", "木曜日に学校へ行きます。", "Vou à escola na quinta.", "木 = árvore."),
            ("金曜日", "きんようび", "kinyoubi", "Sexta-feira", "substantivo", "金曜日に映画を見ます。", "Vou ao cinema na sexta.", "金 = ouro/dinheiro."),
            ("土曜日", "どようび", "doyoubi", "Sábado", "substantivo", "土曜日は休みです。", "Sábado é folga.", "土 = terra."),
            ("日曜日", "にちようび", "nichiyoubi", "Domingo", "substantivo", "日曜日に家にいます。", "Fico em casa no domingo.", "日 = sol/dia."),
            ("週", "しゅう", "shuu", "Semana", "substantivo", "今週は忙しいです。", "Esta semana está cheia.", None),
            ("今週", "こんしゅう", "konshuu", "Esta semana", "substantivo", "今週の土曜日に行きます。", "Vou no sábado desta semana.", None),
            ("来週", "らいしゅう", "raishuu", "Semana que vem", "substantivo", "来週会いましょう。", "Vamos nos ver semana que vem.", None),
            ("先週", "せんしゅう", "senshuu", "Semana passada", "substantivo", "先週は雨でした。", "Semana passada choveu.", None),
        ],
    },
    {
        "slug": "tempo-data",
        "titulo": "Tempo, horas e datas",
        "descricao": "Como falar de hoje, amanhã, horas e meses.",
        "palavras": [
            ("今日", "きょう", "kyou", "Hoje", "substantivo", "今日はいい天気です。", "Hoje está bom tempo.", None),
            ("明日", "あした", "ashita", "Amanhã", "substantivo", "明日学校へ行きます。", "Amanhã vou à escola.", None),
            ("昨日", "きのう", "kinou", "Ontem", "substantivo", "昨日映画を見ました。", "Ontem vi um filme.", None),
            ("今", "いま", "ima", "Agora", "substantivo", "今、何時ですか。", "Que horas são agora?", None),
            ("朝", "あさ", "asa", "Manhã", "substantivo", "朝ご飯を食べました。", "Tomei café da manhã.", None),
            ("昼", "ひる", "hiru", "Meio-dia / Tarde", "substantivo", "昼ご飯を食べます。", "Vou almoçar.", None),
            ("夜", "よる", "yoru", "Noite", "substantivo", "夜は静かです。", "À noite é silencioso.", None),
            ("時", "じ", "ji", "Hora (no relógio)", "contador", "三時です。", "São três horas.", None),
            ("分", "ふん／ぷん", "fun / pun", "Minuto", "contador", "十分待ってください。", "Espere 10 minutos.", None),
            ("年", "ねん", "nen", "Ano", "substantivo", "去年日本へ行きました。", "Ano passado fui ao Japão.", None),
            ("月", "つき／がつ", "tsuki / gatsu", "Mês / Lua", "substantivo", "三月に来ます。", "Venho em março.", None),
            ("日", "ひ／にち", "hi / nichi", "Dia / Sol", "substantivo", "今日は何日ですか。", "Que dia é hoje?", None),
        ],
    },
    {
        "slug": "familia",
        "titulo": "Família",
        "descricao": "Atenção: a forma de chamar muda para sua família e a dos outros.",
        "palavras": [
            ("家族", "かぞく", "kazoku", "Família", "substantivo", "家族は四人です。", "Somos quatro na família.", None),
            ("父", "ちち", "chichi", "Meu pai", "substantivo", "父は会社員です。", "Meu pai é funcionário.", "Para o pai de outra pessoa: お父さん."),
            ("お父さん", "おとうさん", "otou-san", "Pai (de outro / vocativo)", "substantivo", "お父さんはどこですか。", "Onde está seu pai?", None),
            ("母", "はは", "haha", "Minha mãe", "substantivo", "母は先生です。", "Minha mãe é professora.", "Para a mãe de outra pessoa: お母さん."),
            ("お母さん", "おかあさん", "okaa-san", "Mãe (de outro / vocativo)", "substantivo", "お母さんは元気ですか。", "Sua mãe está bem?", None),
            ("兄", "あに", "ani", "Meu irmão mais velho", "substantivo", "兄は大学生です。", "Meu irmão é universitário.", None),
            ("お兄さん", "おにいさん", "onii-san", "Irmão mais velho (de outro)", "substantivo", "お兄さんは何歳ですか。", "Quantos anos tem seu irmão?", None),
            ("姉", "あね", "ane", "Minha irmã mais velha", "substantivo", "姉は二十五歳です。", "Minha irmã tem 25 anos.", None),
            ("お姉さん", "おねえさん", "onee-san", "Irmã mais velha (de outra)", "substantivo", "お姉さんは結婚していますか。", "Sua irmã é casada?", None),
            ("弟", "おとうと", "otouto", "Irmão mais novo", "substantivo", "弟は高校生です。", "Meu irmão mais novo é colegial.", None),
            ("妹", "いもうと", "imouto", "Irmã mais nova", "substantivo", "妹は十歳です。", "Minha irmã tem 10 anos.", None),
        ],
    },
    {
        "slug": "verbos-cotidianos",
        "titulo": "Verbos do dia a dia",
        "descricao": "Os verbos mais usados — todos na forma -masu.",
        "palavras": [
            ("食べる", "たべる", "taberu", "Comer", "verbo (ru)", "ご飯を食べます。", "Vou comer.", None),
            ("飲む", "のむ", "nomu", "Beber", "verbo (u)", "水を飲みます。", "Vou beber água.", None),
            ("見る", "みる", "miru", "Ver / Assistir", "verbo (ru)", "映画を見ます。", "Vou ver um filme.", None),
            ("聞く", "きく", "kiku", "Ouvir / Perguntar", "verbo (u)", "音楽を聞きます。", "Vou ouvir música.", None),
            ("話す", "はなす", "hanasu", "Falar", "verbo (u)", "日本語を話します。", "Falo japonês.", None),
            ("読む", "よむ", "yomu", "Ler", "verbo (u)", "本を読みます。", "Vou ler um livro.", None),
            ("書く", "かく", "kaku", "Escrever", "verbo (u)", "手紙を書きます。", "Vou escrever uma carta.", None),
            ("買う", "かう", "kau", "Comprar", "verbo (u)", "パンを買います。", "Vou comprar pão.", None),
            ("する", "する", "suru", "Fazer", "verbo (irregular)", "勉強します。", "Vou estudar.", "Forma inúmeros verbos: 勉強する, 運動する."),
            ("する (勉強)", "べんきょうする", "benkyou suru", "Estudar", "verbo (irregular)", "日本語を勉強します。", "Vou estudar japonês.", None),
            ("寝る", "ねる", "neru", "Dormir", "verbo (ru)", "十時に寝ます。", "Durmo às dez.", None),
            ("起きる", "おきる", "okiru", "Levantar / Acordar", "verbo (ru)", "六時に起きます。", "Acordo às seis.", None),
        ],
    },
    {
        "slug": "verbos-movimento",
        "titulo": "Verbos de movimento",
        "descricao": "Ir, vir, voltar e suas partículas (へ, に).",
        "palavras": [
            ("行く", "いく", "iku", "Ir", "verbo (u)", "学校へ行きます。", "Vou para a escola.", "Irregular no negativo: 行きません, 行きませんでした."),
            ("来る", "くる", "kuru", "Vir", "verbo (irregular)", "明日来ます。", "Venho amanhã.", "Forma -masu: きます."),
            ("帰る", "かえる", "kaeru", "Voltar (para casa)", "verbo (u)", "家へ帰ります。", "Vou voltar para casa.", "Exceção: parece ru-verb mas é u-verb."),
            ("歩く", "あるく", "aruku", "Caminhar / Andar", "verbo (u)", "公園を歩きます。", "Vou caminhar no parque.", None),
            ("走る", "はしる", "hashiru", "Correr", "verbo (u)", "毎朝走ります。", "Corro toda manhã.", "Exceção: parece ru-verb mas é u-verb."),
            ("乗る", "のる", "noru", "Embarcar / Pegar (transporte)", "verbo (u)", "電車に乗ります。", "Vou pegar o trem.", "Partícula に."),
            ("降りる", "おりる", "oriru", "Descer (de transporte)", "verbo (ru)", "次の駅で降ります。", "Desço na próxima estação.", None),
            ("出る", "でる", "deru", "Sair", "verbo (ru)", "家を出ます。", "Saio de casa.", None),
            ("入る", "はいる", "hairu", "Entrar", "verbo (u)", "部屋に入ります。", "Entro no quarto.", "Exceção: parece ru-verb mas é u-verb."),
            ("着く", "つく", "tsuku", "Chegar", "verbo (u)", "駅に着きました。", "Cheguei na estação.", None),
            ("止まる", "とまる", "tomaru", "Parar", "verbo (u)", "電車が止まりました。", "O trem parou.", None),
            ("曲がる", "まがる", "magaru", "Virar (em direção)", "verbo (u)", "右に曲がってください。", "Vire à direita, por favor.", None),
        ],
    },
    {
        "slug": "adjetivos-i",
        "titulo": "Adjetivos i (い)",
        "descricao": "Terminam em い e conjugam direto. Exceção: いい (bom).",
        "palavras": [
            ("大きい", "おおきい", "ookii", "Grande", "adjetivo i", "大きい家です。", "É uma casa grande.", None),
            ("小さい", "ちいさい", "chiisai", "Pequeno", "adjetivo i", "小さい犬がいます。", "Há um cachorro pequeno.", None),
            ("新しい", "あたらしい", "atarashii", "Novo", "adjetivo i", "新しい車を買いました。", "Comprei um carro novo.", None),
            ("古い", "ふるい", "furui", "Velho (coisa)", "adjetivo i", "古い本です。", "É um livro velho.", "Para pessoa, use 年を取る."),
            ("高い", "たかい", "takai", "Caro / Alto", "adjetivo i", "この本は高いです。", "Este livro é caro.", None),
            ("安い", "やすい", "yasui", "Barato", "adjetivo i", "安いレストランです。", "É um restaurante barato.", None),
            ("いい", "いい", "ii", "Bom", "adjetivo i (irregular)", "いい天気ですね。", "Está bom tempo, né?", "No passado vira よかった, não いかった."),
            ("悪い", "わるい", "warui", "Ruim", "adjetivo i", "天気が悪いです。", "O tempo está ruim.", None),
            ("暑い", "あつい", "atsui", "Quente (clima)", "adjetivo i", "今日は暑いです。", "Hoje está quente.", None),
            ("寒い", "さむい", "samui", "Frio (clima)", "adjetivo i", "冬は寒いです。", "O inverno é frio.", None),
            ("おいしい", "おいしい", "oishii", "Gostoso", "adjetivo i", "このパンはおいしいです。", "Este pão é gostoso.", None),
            ("難しい", "むずかしい", "muzukashii", "Difícil", "adjetivo i", "日本語は難しいです。", "Japonês é difícil.", None),
            ("やさしい", "やさしい", "yasashii", "Fácil / Gentil", "adjetivo i", "やさしい先生です。", "É um professor gentil.", None),
        ],
    },
    {
        "slug": "adjetivos-na",
        "titulo": "Adjetivos na (な)",
        "descricao": "Precisam de な antes de substantivo: きれいな花.",
        "palavras": [
            ("きれい", "きれい", "kirei", "Bonito / Limpo", "adjetivo na", "きれいな部屋ですね。", "Que quarto bonito.", "Apesar de terminar em い, é adjetivo na."),
            ("元気", "げんき", "genki", "Bem (de saúde) / Animado", "adjetivo na", "元気ですか。", "Você está bem?", None),
            ("有名", "ゆうめい", "yuumei", "Famoso", "adjetivo na", "有名な歌手です。", "É um cantor famoso.", None),
            ("親切", "しんせつ", "shinsetsu", "Gentil / Prestativo", "adjetivo na", "親切な人です。", "É uma pessoa gentil.", None),
            ("便利", "べんり", "benri", "Conveniente / Prático", "adjetivo na", "このアプリは便利です。", "Este app é prático.", None),
            ("不便", "ふべん", "fuben", "Inconveniente", "adjetivo na", "ここは不便です。", "Aqui é inconveniente.", None),
            ("静か", "しずか", "shizuka", "Silencioso", "adjetivo na", "静かな町です。", "É uma cidade silenciosa.", None),
            ("にぎやか", "にぎやか", "nigiyaka", "Movimentado / Animado", "adjetivo na", "にぎやかな町です。", "É uma cidade movimentada.", None),
            ("好き", "すき", "suki", "Gostar", "adjetivo na", "音楽が好きです。", "Gosto de música.", "Partícula が, não を."),
            ("嫌い", "きらい", "kirai", "Não gostar / Odiar", "adjetivo na", "虫が嫌いです。", "Odeio insetos.", None),
            ("上手", "じょうず", "jouzu", "Bom em (habilidade)", "adjetivo na", "日本語が上手ですね。", "Você é bom em japonês.", "Não use para si mesmo."),
            ("下手", "へた", "heta", "Ruim em (habilidade)", "adjetivo na", "料理が下手です。", "Sou ruim em cozinhar.", None),
        ],
    },
    {
        "slug": "cores",
        "titulo": "Cores",
        "descricao": "Algumas cores são adjetivos i, outras são substantivos.",
        "palavras": [
            ("赤", "あか", "aka", "Vermelho", "substantivo", "赤が好きです。", "Gosto de vermelho.", "Forma adjetivo i: 赤い."),
            ("青", "あお", "ao", "Azul", "substantivo", "青い空ですね。", "Que céu azul.", "Tradicionalmente cobre verde também."),
            ("白", "しろ", "shiro", "Branco", "substantivo", "白い犬がいます。", "Há um cachorro branco.", None),
            ("黒", "くろ", "kuro", "Preto", "substantivo", "黒い車です。", "É um carro preto.", None),
            ("黄色", "きいろ", "kiiro", "Amarelo", "substantivo", "黄色いシャツを着ます。", "Visto uma camisa amarela.", None),
            ("緑", "みどり", "midori", "Verde", "substantivo", "緑のお茶を飲みます。", "Vou beber chá verde.", "Para verde-azulado tradicional, usa-se 青."),
            ("茶色", "ちゃいろ", "chairo", "Marrom", "substantivo", "茶色いかばんです。", "É uma bolsa marrom.", "Literalmente 'cor de chá'."),
            ("ピンク", "ピンク", "pinku", "Rosa (cor)", "substantivo", "ピンクの花です。", "É uma flor rosa.", None),
            ("オレンジ", "オレンジ", "orenji", "Laranja (cor)", "substantivo", "オレンジ色が好きです。", "Gosto de laranja.", None),
            ("紫", "むらさき", "murasaki", "Roxo", "substantivo", "紫の花です。", "É uma flor roxa.", None),
            ("灰色", "はいいろ", "haiiro", "Cinza", "substantivo", "灰色の雲です。", "São nuvens cinzas.", None),
            ("色", "いろ", "iro", "Cor", "substantivo", "好きな色は何ですか。", "Qual é sua cor favorita?", None),
        ],
    },
    {
        "slug": "comida-bebida",
        "titulo": "Comida e bebida",
        "descricao": "Itens para o restaurante e o supermercado.",
        "palavras": [
            ("ご飯", "ごはん", "gohan", "Arroz / Refeição", "substantivo", "ご飯を食べましょう。", "Vamos comer.", None),
            ("パン", "パン", "pan", "Pão", "substantivo", "朝にパンを食べます。", "Como pão de manhã.", "Do português pão."),
            ("肉", "にく", "niku", "Carne", "substantivo", "肉が好きです。", "Gosto de carne.", None),
            ("魚", "さかな", "sakana", "Peixe", "substantivo", "魚を焼きます。", "Vou grelhar peixe.", None),
            ("野菜", "やさい", "yasai", "Verdura / Legume", "substantivo", "野菜を食べてください。", "Coma verduras, por favor.", None),
            ("果物", "くだもの", "kudamono", "Fruta", "substantivo", "果物が好きです。", "Gosto de frutas.", None),
            ("水", "みず", "mizu", "Água", "substantivo", "水を一杯ください。", "Um copo d'água, por favor.", None),
            ("お茶", "おちゃ", "ocha", "Chá (verde)", "substantivo", "お茶を飲みます。", "Vou tomar chá.", None),
            ("コーヒー", "コーヒー", "koohii", "Café", "substantivo", "コーヒーを一杯ください。", "Um café, por favor.", None),
            ("牛乳", "ぎゅうにゅう", "gyuunyuu", "Leite", "substantivo", "牛乳が好きです。", "Gosto de leite.", None),
            ("お酒", "おさけ", "osake", "Bebida alcoólica / Saquê", "substantivo", "お酒を飲みません。", "Não bebo álcool.", None),
            ("ラーメン", "ラーメン", "raamen", "Lámen", "substantivo", "ラーメンを食べました。", "Comi lámen.", None),
        ],
    },
    {
        "slug": "lugares",
        "titulo": "Lugares comuns",
        "descricao": "Onde a gente vai todo dia.",
        "palavras": [
            ("家", "いえ／うち", "ie / uchi", "Casa", "substantivo", "家に帰ります。", "Vou para casa.", None),
            ("学校", "がっこう", "gakkou", "Escola", "substantivo", "学校へ行きます。", "Vou para a escola.", None),
            ("会社", "かいしゃ", "kaisha", "Empresa", "substantivo", "会社で働きます。", "Trabalho na empresa.", None),
            ("駅", "えき", "eki", "Estação (de trem)", "substantivo", "駅で待ってください。", "Espere na estação.", None),
            ("店", "みせ", "mise", "Loja", "substantivo", "店で買い物します。", "Faço compras na loja.", None),
            ("レストラン", "レストラン", "resutoran", "Restaurante", "substantivo", "レストランで食べます。", "Como no restaurante.", None),
            ("病院", "びょういん", "byouin", "Hospital", "substantivo", "病院へ行きます。", "Vou ao hospital.", None),
            ("銀行", "ぎんこう", "ginkou", "Banco", "substantivo", "銀行はどこですか。", "Onde fica o banco?", None),
            ("公園", "こうえん", "kouen", "Parque", "substantivo", "公園で遊びます。", "Vou brincar no parque.", None),
            ("図書館", "としょかん", "toshokan", "Biblioteca", "substantivo", "図書館で勉強します。", "Estudo na biblioteca.", None),
            ("郵便局", "ゆうびんきょく", "yuubinkyoku", "Correios", "substantivo", "郵便局で切手を買います。", "Compro selos no correio.", None),
            ("空港", "くうこう", "kuukou", "Aeroporto", "substantivo", "空港へ行きます。", "Vou ao aeroporto.", None),
        ],
    },
    {
        "slug": "casa",
        "titulo": "Em casa: cômodos e objetos",
        "descricao": "Vocabulário do ambiente doméstico.",
        "palavras": [
            ("部屋", "へや", "heya", "Quarto / Cômodo", "substantivo", "私の部屋は二階です。", "Meu quarto fica no 2º andar.", None),
            ("台所", "だいどころ", "daidokoro", "Cozinha", "substantivo", "台所で料理します。", "Cozinho na cozinha.", None),
            ("お風呂", "おふろ", "ofuro", "Banheira / Banho", "substantivo", "お風呂に入ります。", "Vou tomar banho.", None),
            ("トイレ", "トイレ", "toire", "Banheiro / Privada", "substantivo", "トイレはどこですか。", "Onde fica o banheiro?", None),
            ("机", "つくえ", "tsukue", "Mesa de estudo", "substantivo", "机の上に本があります。", "Há um livro sobre a mesa.", None),
            ("椅子", "いす", "isu", "Cadeira", "substantivo", "椅子に座ってください。", "Sente-se na cadeira.", None),
            ("ベッド", "ベッド", "beddo", "Cama", "substantivo", "ベッドで寝ます。", "Durmo na cama.", None),
            ("窓", "まど", "mado", "Janela", "substantivo", "窓を開けてください。", "Abra a janela, por favor.", None),
            ("ドア", "ドア", "doa", "Porta", "substantivo", "ドアを閉めてください。", "Feche a porta, por favor.", None),
            ("電話", "でんわ", "denwa", "Telefone", "substantivo", "電話をかけます。", "Vou ligar.", None),
            ("テレビ", "テレビ", "terebi", "Televisão", "substantivo", "テレビを見ます。", "Vou ver TV.", None),
            ("時計", "とけい", "tokei", "Relógio", "substantivo", "時計を見ます。", "Olho o relógio.", None),
        ],
    },
    {
        "slug": "direcoes-posicao",
        "titulo": "Direções e posições",
        "descricao": "Em cima, embaixo, dentro, fora — orientação espacial.",
        "palavras": [
            ("上", "うえ", "ue", "Em cima", "substantivo", "机の上に本があります。", "Há um livro sobre a mesa.", None),
            ("下", "した", "shita", "Embaixo", "substantivo", "椅子の下に猫がいます。", "Há um gato embaixo da cadeira.", None),
            ("中", "なか", "naka", "Dentro / Meio", "substantivo", "箱の中に何がありますか。", "O que tem dentro da caixa?", None),
            ("外", "そと", "soto", "Fora", "substantivo", "外は寒いです。", "Está frio lá fora.", None),
            ("前", "まえ", "mae", "Frente / Antes", "substantivo", "駅の前で会いましょう。", "Vamos nos encontrar em frente à estação.", None),
            ("後ろ", "うしろ", "ushiro", "Atrás", "substantivo", "家の後ろに公園があります。", "Há um parque atrás de casa.", None),
            ("右", "みぎ", "migi", "Direita", "substantivo", "右に曲がってください。", "Vire à direita.", None),
            ("左", "ひだり", "hidari", "Esquerda", "substantivo", "左に銀行があります。", "À esquerda tem um banco.", None),
            ("隣", "となり", "tonari", "Ao lado", "substantivo", "隣の人は誰ですか。", "Quem é a pessoa do lado?", None),
            ("近く", "ちかく", "chikaku", "Perto", "substantivo", "駅の近くに住んでいます。", "Moro perto da estação.", None),
            ("遠く", "とおく", "tooku", "Longe", "substantivo", "遠くに山が見えます。", "Vê-se uma montanha ao longe.", None),
            ("間", "あいだ", "aida", "Entre", "substantivo", "銀行と店の間にあります。", "Fica entre o banco e a loja.", None),
        ],
    },
    {
        "slug": "particulas-basicas",
        "titulo": "Partículas básicas",
        "descricao": "Coladinhos pequenos que mudam o sentido da frase.",
        "palavras": [
            ("は", "は", "wa", "Partícula de tópico", "partícula", "私は学生です。", "Eu sou estudante.", "Escrita は mas lida 'wa'."),
            ("が", "が", "ga", "Partícula de sujeito", "partícula", "雨が降ります。", "Vai chover.", "Marca o sujeito (foco)."),
            ("を", "を", "wo / o", "Partícula de objeto", "partícula", "本を読みます。", "Vou ler um livro.", "Sempre objeto direto."),
            ("に", "に", "ni", "Em / Para / Às (tempo, local)", "partícula", "七時に起きます。", "Acordo às sete.", None),
            ("で", "で", "de", "Em (local de ação) / Por meio de", "partícula", "学校で勉強します。", "Estudo na escola.", None),
            ("へ", "へ", "e", "Em direção a", "partícula", "東京へ行きます。", "Vou para Tóquio.", "Escrita へ mas lida 'e'."),
            ("と", "と", "to", "E / Com", "partícula", "友達と行きます。", "Vou com um amigo.", None),
            ("も", "も", "mo", "Também", "partícula", "私も学生です。", "Eu também sou estudante.", None),
            ("の", "の", "no", "De (posse / ligação)", "partícula", "私の本です。", "É meu livro.", None),
            ("か", "か", "ka", "Marca pergunta", "partícula", "元気ですか。", "Está bem?", "Fica no fim da frase."),
            ("から", "から", "kara", "De / Desde", "partícula", "九時から始まります。", "Começa às nove.", None),
            ("まで", "まで", "made", "Até", "partícula", "五時まで働きます。", "Trabalho até as cinco.", None),
        ],
    },
    {
        "slug": "demonstrativos",
        "titulo": "Demonstrativos (kosoado)",
        "descricao": "Sistema こ／そ／あ／ど — perto, longe, mais longe, pergunta.",
        "palavras": [
            ("これ", "これ", "kore", "Isto (perto de mim)", "pronome", "これは本です。", "Isto é um livro.", None),
            ("それ", "それ", "sore", "Isso (perto de você)", "pronome", "それは何ですか。", "O que é isso?", None),
            ("あれ", "あれ", "are", "Aquilo (longe dos dois)", "pronome", "あれは私の車です。", "Aquilo é meu carro.", None),
            ("どれ", "どれ", "dore", "Qual?", "pronome", "どれがいいですか。", "Qual está bom?", None),
            ("この", "この", "kono", "Este (+ subst.)", "adjetivo", "この本は私のです。", "Este livro é meu.", "Sempre seguido de substantivo."),
            ("その", "その", "sono", "Esse (+ subst.)", "adjetivo", "その人は誰ですか。", "Quem é essa pessoa?", None),
            ("あの", "あの", "ano", "Aquele (+ subst.)", "adjetivo", "あの建物は何ですか。", "Que prédio é aquele?", None),
            ("どの", "どの", "dono", "Qual (+ subst.)?", "adjetivo", "どの色が好きですか。", "Qual cor você gosta?", None),
            ("ここ", "ここ", "koko", "Aqui", "pronome", "ここはどこですか。", "Que lugar é este?", None),
            ("そこ", "そこ", "soko", "Aí", "pronome", "そこに座ってください。", "Sente-se aí, por favor.", None),
            ("あそこ", "あそこ", "asoko", "Lá", "pronome", "あそこに駅があります。", "Lá tem uma estação.", None),
            ("どこ", "どこ", "doko", "Onde?", "pronome", "トイレはどこですか。", "Onde fica o banheiro?", None),
        ],
    },
    {
        "slug": "interrogativos",
        "titulo": "Pronomes interrogativos",
        "descricao": "Como fazer as perguntas básicas.",
        "palavras": [
            ("何", "なに／なん", "nani / nan", "O quê?", "pronome", "これは何ですか。", "O que é isto?", "Vira なん antes de です e contadores."),
            ("誰", "だれ", "dare", "Quem?", "pronome", "あの人は誰ですか。", "Quem é aquela pessoa?", None),
            ("いつ", "いつ", "itsu", "Quando?", "pronome", "いつ来ますか。", "Quando você vem?", None),
            ("どこ", "どこ", "doko", "Onde?", "pronome", "どこへ行きますか。", "Para onde você vai?", None),
            ("どうして", "どうして", "doushite", "Por quê?", "pronome", "どうして遅れましたか。", "Por que se atrasou?", None),
            ("なぜ", "なぜ", "naze", "Por quê? (mais formal)", "pronome", "なぜですか。", "Por quê?", None),
            ("どう", "どう", "dou", "Como (está)?", "pronome", "天気はどうですか。", "Como está o tempo?", None),
            ("いくら", "いくら", "ikura", "Quanto custa?", "pronome", "これはいくらですか。", "Quanto custa isto?", None),
            ("いくつ", "いくつ", "ikutsu", "Quantos / Quantos anos?", "pronome", "おいくつですか。", "Quantos anos você tem?", None),
            ("何時", "なんじ", "nanji", "Que horas?", "pronome", "今何時ですか。", "Que horas são agora?", None),
            ("何歳", "なんさい", "nansai", "Quantos anos?", "pronome", "何歳ですか。", "Quantos anos você tem?", None),
            ("どんな", "どんな", "donna", "Que tipo de?", "pronome", "どんな本が好きですか。", "Que tipo de livro você gosta?", None),
        ],
    },
    {
        "slug": "adverbios",
        "titulo": "Advérbios de tempo e frequência",
        "descricao": "Sempre, às vezes, ainda, já — temperando as frases.",
        "palavras": [
            ("いつも", "いつも", "itsumo", "Sempre", "advérbio", "いつもコーヒーを飲みます。", "Sempre tomo café.", None),
            ("よく", "よく", "yoku", "Frequentemente / Bem", "advérbio", "よく映画を見ます。", "Vejo filmes frequentemente.", None),
            ("時々", "ときどき", "tokidoki", "Às vezes", "advérbio", "時々日本料理を食べます。", "Às vezes como comida japonesa.", None),
            ("たまに", "たまに", "tamani", "Raramente / De vez em quando", "advérbio", "たまに散歩します。", "Caminho de vez em quando.", None),
            ("あまり", "あまり", "amari", "Não muito (+ negativo)", "advérbio", "あまり食べません。", "Não como muito.", "Sempre com verbo negativo."),
            ("全然", "ぜんぜん", "zenzen", "Nada / Em absoluto (+ neg.)", "advérbio", "全然分かりません。", "Não entendo nada.", "Sempre com verbo negativo."),
            ("もう", "もう", "mou", "Já", "advérbio", "もう食べました。", "Já comi.", None),
            ("まだ", "まだ", "mada", "Ainda", "advérbio", "まだ食べていません。", "Ainda não comi.", None),
            ("すぐ", "すぐ", "sugu", "Logo / Imediatamente", "advérbio", "すぐ行きます。", "Já vou.", None),
            ("ゆっくり", "ゆっくり", "yukkuri", "Devagar", "advérbio", "ゆっくり話してください。", "Fale devagar, por favor.", None),
            ("少し", "すこし", "sukoshi", "Um pouco", "advérbio", "少し疲れました。", "Estou um pouco cansado.", None),
            ("たくさん", "たくさん", "takusan", "Muito (quantidade)", "advérbio", "たくさん食べました。", "Comi muito.", None),
        ],
    },
    {
        "slug": "corpo",
        "titulo": "Corpo humano",
        "descricao": "Partes do corpo — útil para falar de saúde.",
        "palavras": [
            ("頭", "あたま", "atama", "Cabeça", "substantivo", "頭が痛いです。", "Estou com dor de cabeça.", None),
            ("顔", "かお", "kao", "Rosto", "substantivo", "顔を洗います。", "Vou lavar o rosto.", None),
            ("目", "め", "me", "Olho", "substantivo", "目が大きいです。", "Tem olhos grandes.", None),
            ("耳", "みみ", "mimi", "Orelha", "substantivo", "耳が痛いです。", "Estou com dor de ouvido.", None),
            ("鼻", "はな", "hana", "Nariz", "substantivo", "鼻が長いです。", "Tem nariz comprido.", "Mesmo som que 花 (flor)."),
            ("口", "くち", "kuchi", "Boca", "substantivo", "口を開けてください。", "Abra a boca, por favor.", None),
            ("歯", "は", "ha", "Dente", "substantivo", "歯を磨きます。", "Vou escovar os dentes.", None),
            ("手", "て", "te", "Mão", "substantivo", "手を洗ってください。", "Lave as mãos, por favor.", None),
            ("足", "あし", "ashi", "Pé / Perna", "substantivo", "足が痛いです。", "Meu pé dói.", None),
            ("お腹", "おなか", "onaka", "Barriga", "substantivo", "お腹がすきました。", "Estou com fome.", None),
            ("背中", "せなか", "senaka", "Costas", "substantivo", "背中が痛いです。", "Estou com dor nas costas.", None),
            ("髪", "かみ", "kami", "Cabelo", "substantivo", "髪が長いです。", "Tem cabelo comprido.", None),
        ],
    },
    {
        "slug": "clima-natureza",
        "titulo": "Clima e natureza",
        "descricao": "Falar do tempo é começo de qualquer conversa.",
        "palavras": [
            ("天気", "てんき", "tenki", "Tempo (clima)", "substantivo", "天気がいいですね。", "Está bom tempo, né?", None),
            ("雨", "あめ", "ame", "Chuva", "substantivo", "雨が降っています。", "Está chovendo.", "Mesmo kanji que 飴 (doce)."),
            ("雪", "ゆき", "yuki", "Neve", "substantivo", "雪が降ります。", "Vai nevar.", None),
            ("雲", "くも", "kumo", "Nuvem", "substantivo", "雲が多いです。", "Há muitas nuvens.", None),
            ("風", "かぜ", "kaze", "Vento", "substantivo", "風が強いです。", "Está ventando forte.", "Também 'resfriado'."),
            ("空", "そら", "sora", "Céu", "substantivo", "空が青いです。", "O céu está azul.", None),
            ("太陽", "たいよう", "taiyou", "Sol", "substantivo", "太陽が出ています。", "O sol está alto.", None),
            ("山", "やま", "yama", "Montanha", "substantivo", "山に登ります。", "Vou subir a montanha.", None),
            ("川", "かわ", "kawa", "Rio", "substantivo", "川で泳ぎます。", "Vou nadar no rio.", None),
            ("海", "うみ", "umi", "Mar", "substantivo", "夏に海へ行きます。", "Vou ao mar no verão.", None),
            ("木", "き", "ki", "Árvore", "substantivo", "公園に木があります。", "Há árvores no parque.", None),
            ("花", "はな", "hana", "Flor", "substantivo", "きれいな花ですね。", "Que flor bonita.", None),
        ],
    },
    {
        "slug": "estacoes-meses",
        "titulo": "Estações e meses",
        "descricao": "Os meses são literalmente '1-ª lua, 2-ª lua...'.",
        "palavras": [
            ("春", "はる", "haru", "Primavera", "substantivo", "春は暖かいです。", "A primavera é morna.", None),
            ("夏", "なつ", "natsu", "Verão", "substantivo", "夏が好きです。", "Gosto do verão.", None),
            ("秋", "あき", "aki", "Outono", "substantivo", "秋は涼しいです。", "O outono é fresco.", None),
            ("冬", "ふゆ", "fuyu", "Inverno", "substantivo", "冬は寒いです。", "O inverno é frio.", None),
            ("一月", "いちがつ", "ichigatsu", "Janeiro", "substantivo", "一月一日は祝日です。", "1º de janeiro é feriado.", None),
            ("二月", "にがつ", "nigatsu", "Fevereiro", "substantivo", "二月は短いです。", "Fevereiro é curto.", None),
            ("三月", "さんがつ", "sangatsu", "Março", "substantivo", "三月に卒業します。", "Vou me formar em março.", None),
            ("四月", "しがつ", "shigatsu", "Abril", "substantivo", "四月に学校が始まります。", "A escola começa em abril.", "Note: しがつ, não よんがつ."),
            ("五月", "ごがつ", "gogatsu", "Maio", "substantivo", "五月は休みが多いです。", "Há muitos feriados em maio.", None),
            ("六月", "ろくがつ", "rokugatsu", "Junho", "substantivo", "六月は梅雨です。", "Junho é estação chuvosa.", None),
            ("七月", "しちがつ", "shichigatsu", "Julho", "substantivo", "七月は暑いです。", "Julho é quente.", "Note: しちがつ."),
            ("十二月", "じゅうにがつ", "juunigatsu", "Dezembro", "substantivo", "十二月にクリスマスがあります。", "Em dezembro tem Natal.", None),
        ],
    },
    {
        "slug": "expressoes-uteis",
        "titulo": "Expressões úteis do dia a dia",
        "descricao": "Frases prontas que aparecem o tempo todo.",
        "palavras": [
            ("いただきます", "いただきます", "itadakimasu", "Antes de comer (obrigado pela comida)", "expressão", "いただきます！", "Vou comer!", "Sempre antes da refeição."),
            ("ごちそうさま", "ごちそうさま", "gochisousama", "Depois de comer (obrigado pela comida)", "expressão", "ごちそうさまでした。", "Estava ótimo, obrigado.", None),
            ("お願いします", "おねがいします", "onegaishimasu", "Por favor", "expressão", "コーヒーをお願いします。", "Um café, por favor.", None),
            ("どうぞ", "どうぞ", "douzo", "Por favor (entregando algo)", "expressão", "どうぞ、お先に。", "Por favor, pode ir na frente.", None),
            ("どういたしまして", "どういたしまして", "douitashimashite", "De nada", "expressão", "「ありがとう」「どういたしまして」", "'Obrigado' 'De nada'", None),
            ("お元気で", "おげんきで", "ogenki de", "Passe bem", "expressão", "お元気で。", "Cuide-se.", "Despedida mais longa."),
            ("頑張って", "がんばって", "ganbatte", "Boa sorte / Dê o seu melhor", "expressão", "テスト、頑張って！", "Boa sorte na prova!", None),
            ("お疲れ様", "おつかれさま", "otsukaresama", "Obrigado pelo trabalho", "expressão", "お疲れ様でした。", "Obrigado pelo esforço.", "Fim de expediente."),
            ("分かりました", "わかりました", "wakarimashita", "Entendi", "expressão", "はい、分かりました。", "Sim, entendi.", None),
            ("分かりません", "わかりません", "wakarimasen", "Não entendi", "expressão", "すみません、分かりません。", "Desculpe, não entendi.", None),
            ("もう一度", "もういちど", "mou ichido", "Mais uma vez", "expressão", "もう一度お願いします。", "Mais uma vez, por favor.", None),
            ("ちょっと待って", "ちょっとまって", "chotto matte", "Espera um pouco", "expressão", "ちょっと待ってください。", "Espere um pouco, por favor.", None),
        ],
    },
]
