"""Estrutura do JLPT N4 — tópicos iniciais para expandir aos poucos."""

NIVEL = {
    "codigo": "N4",
    "nome": "Básico",
    "descricao": "Compreensão de tópicos cotidianos com vocabulário ampliado, ~1500 palavras.",
    "ordem": 2,
}

TOPICOS = [
    {
        "slug": "transporte",
        "titulo": "Transporte",
        "descricao": "Meios de transporte e palavras relacionadas a viagem.",
        "palavras": [
            ("電車", "でんしゃ", "densha", "Trem", "substantivo", "電車で行きます。", "Vou de trem.", None),
            ("地下鉄", "ちかてつ", "chikatetsu", "Metrô", "substantivo", "地下鉄に乗ります。", "Vou pegar o metrô.", None),
            ("バス", "バス", "basu", "Ônibus", "substantivo", "バスで通勤します。", "Vou de ônibus para o trabalho.", None),
            ("タクシー", "タクシー", "takushii", "Táxi", "substantivo", "タクシーを呼びます。", "Vou chamar um táxi.", None),
            ("自転車", "じてんしゃ", "jitensha", "Bicicleta", "substantivo", "自転車で行きます。", "Vou de bicicleta.", None),
            ("車", "くるま", "kuruma", "Carro", "substantivo", "車を運転します。", "Vou dirigir o carro.", None),
            ("飛行機", "ひこうき", "hikouki", "Avião", "substantivo", "飛行機で日本へ行きます。", "Vou ao Japão de avião.", None),
            ("船", "ふね", "fune", "Barco / Navio", "substantivo", "船で旅行しました。", "Viajei de navio.", None),
            ("切符", "きっぷ", "kippu", "Bilhete / Passagem", "substantivo", "切符を買います。", "Vou comprar o bilhete.", None),
            ("駅員", "えきいん", "ekiin", "Funcionário da estação", "substantivo", "駅員に聞きました。", "Perguntei ao funcionário.", None),
            ("通勤", "つうきん", "tsuukin", "Ir ao trabalho (commute)", "substantivo", "通勤に一時間かかります。", "Demoro 1h para chegar ao trabalho.", None),
            ("運転", "うんてん", "unten", "Dirigir (substantivo)", "substantivo", "運転は得意です。", "Sou bom em dirigir.", "Com する vira verbo."),
        ],
    },
    {
        "slug": "trabalho-profissoes",
        "titulo": "Trabalho e profissões",
        "descricao": "Vocabulário do dia a dia profissional.",
        "palavras": [
            ("仕事", "しごと", "shigoto", "Trabalho", "substantivo", "仕事が忙しいです。", "O trabalho está cheio.", None),
            ("会議", "かいぎ", "kaigi", "Reunião", "substantivo", "明日会議があります。", "Amanhã tem reunião.", None),
            ("社員", "しゃいん", "shain", "Funcionário (de empresa)", "substantivo", "新しい社員が来ました。", "Chegou um novo funcionário.", None),
            ("部長", "ぶちょう", "buchou", "Chefe de departamento", "substantivo", "部長と話しました。", "Conversei com o chefe.", None),
            ("社長", "しゃちょう", "shachou", "Presidente da empresa", "substantivo", "社長は今いません。", "O presidente não está.", None),
            ("医者", "いしゃ", "isha", "Médico", "substantivo", "医者に行きます。", "Vou ao médico.", None),
            ("看護師", "かんごし", "kangoshi", "Enfermeiro(a)", "substantivo", "彼女は看護師です。", "Ela é enfermeira.", None),
            ("警察官", "けいさつかん", "keisatsukan", "Policial", "substantivo", "警察官に道を聞きました。", "Perguntei o caminho ao policial.", None),
            ("公務員", "こうむいん", "koumuin", "Funcionário público", "substantivo", "父は公務員です。", "Meu pai é funcionário público.", None),
            ("店員", "てんいん", "tenin", "Atendente de loja", "substantivo", "店員に聞いてください。", "Pergunte ao atendente.", None),
            ("給料", "きゅうりょう", "kyuuryou", "Salário", "substantivo", "給料が上がりました。", "Meu salário subiu.", None),
            ("残業", "ざんぎょう", "zangyou", "Hora extra", "substantivo", "今日は残業です。", "Hoje faço hora extra.", None),
        ],
    },
    {
        "slug": "saude-medico",
        "titulo": "Saúde e médico",
        "descricao": "Para uma emergência ou consulta.",
        "palavras": [
            ("病気", "びょうき", "byouki", "Doença", "substantivo", "彼は病気です。", "Ele está doente.", None),
            ("風邪", "かぜ", "kaze", "Resfriado", "substantivo", "風邪をひきました。", "Peguei um resfriado.", None),
            ("熱", "ねつ", "netsu", "Febre", "substantivo", "熱があります。", "Estou com febre.", None),
            ("薬", "くすり", "kusuri", "Remédio", "substantivo", "薬を飲みます。", "Vou tomar remédio.", "Verbo: 飲む (engolir)."),
            ("注射", "ちゅうしゃ", "chuusha", "Injeção", "substantivo", "注射をしました。", "Tomei injeção.", None),
            ("怪我", "けが", "kega", "Ferimento", "substantivo", "怪我をしました。", "Me machuquei.", None),
            ("痛い", "いたい", "itai", "Doloroso / Dói", "adjetivo i", "頭が痛いです。", "Minha cabeça dói.", None),
            ("具合", "ぐあい", "guai", "Condição (de saúde)", "substantivo", "具合が悪いです。", "Estou mal.", None),
            ("元気", "げんき", "genki", "Saudável / Animado", "adjetivo na", "元気になりました。", "Fiquei bem.", None),
            ("休む", "やすむ", "yasumu", "Descansar / Faltar", "verbo (u)", "今日は休みます。", "Hoje vou faltar.", None),
            ("入院", "にゅういん", "nyuuin", "Internação hospitalar", "substantivo", "入院しました。", "Fui internado.", None),
            ("退院", "たいいん", "taiin", "Alta hospitalar", "substantivo", "明日退院します。", "Amanhã recebo alta.", None),
        ],
    },
    {
        "slug": "viagem",
        "titulo": "Viagem",
        "descricao": "Vocabulário essencial para viajar pelo Japão.",
        "palavras": [
            ("旅行", "りょこう", "ryokou", "Viagem", "substantivo", "旅行が好きです。", "Gosto de viajar.", None),
            ("観光", "かんこう", "kankou", "Turismo / Passeio", "substantivo", "京都を観光します。", "Vou fazer turismo em Kyoto.", None),
            ("ホテル", "ホテル", "hoteru", "Hotel", "substantivo", "ホテルを予約しました。", "Reservei o hotel.", None),
            ("旅館", "りょかん", "ryokan", "Pousada tradicional", "substantivo", "旅館に泊まりました。", "Hospedei-me em um ryokan.", None),
            ("予約", "よやく", "yoyaku", "Reserva", "substantivo", "予約があります。", "Tenho reserva.", None),
            ("地図", "ちず", "chizu", "Mapa", "substantivo", "地図を見ます。", "Vou ver o mapa.", None),
            ("案内", "あんない", "annai", "Guia / Orientação", "substantivo", "案内してください。", "Por favor, me guie.", None),
            ("外国", "がいこく", "gaikoku", "Estrangeiro (país)", "substantivo", "外国へ行きたいです。", "Quero ir ao exterior.", None),
            ("国", "くに", "kuni", "País", "substantivo", "どの国から来ましたか。", "De que país você é?", None),
            ("お土産", "おみやげ", "omiyage", "Lembrança / Souvenir", "substantivo", "お土産を買いました。", "Comprei lembranças.", None),
            ("写真", "しゃしん", "shashin", "Foto", "substantivo", "写真を撮ります。", "Vou tirar uma foto.", None),
            ("空港", "くうこう", "kuukou", "Aeroporto", "substantivo", "空港に着きました。", "Cheguei no aeroporto.", None),
        ],
    },
    {
        "slug": "tecnologia",
        "titulo": "Tecnologia e comunicação",
        "descricao": "Computador, internet, celular.",
        "palavras": [
            ("パソコン", "パソコン", "pasokon", "Computador (PC)", "substantivo", "パソコンを使います。", "Vou usar o computador.", "Contração de 'personal computer'."),
            ("携帯", "けいたい", "keitai", "Celular", "substantivo", "携帯を忘れました。", "Esqueci o celular.", "Também 携帯電話."),
            ("スマホ", "スマホ", "sumaho", "Smartphone", "substantivo", "スマホで読みます。", "Vou ler no smartphone.", None),
            ("メール", "メール", "meeru", "E-mail", "substantivo", "メールを送ります。", "Vou enviar um e-mail.", None),
            ("電話", "でんわ", "denwa", "Telefone / Ligação", "substantivo", "電話します。", "Vou ligar.", None),
            ("インターネット", "インターネット", "intaanetto", "Internet", "substantivo", "インターネットで調べます。", "Vou pesquisar na internet.", None),
            ("ウェブサイト", "ウェブサイト", "webusaito", "Site / Website", "substantivo", "ウェブサイトを見ます。", "Vou ver o site.", None),
            ("プログラム", "プログラム", "puroguramu", "Programa", "substantivo", "プログラムを書きます。", "Vou escrever um programa.", None),
            ("ファイル", "ファイル", "fairu", "Arquivo", "substantivo", "ファイルを開きます。", "Vou abrir o arquivo.", None),
            ("ソフト", "ソフト", "sofuto", "Software", "substantivo", "新しいソフトを入れました。", "Instalei um novo software.", None),
            ("使う", "つかう", "tsukau", "Usar", "verbo (u)", "毎日パソコンを使います。", "Uso o computador todo dia.", None),
            ("送る", "おくる", "okuru", "Enviar / Acompanhar", "verbo (u)", "プレゼントを送ります。", "Vou enviar um presente.", None),
        ],
    },
    {
        "slug": "emocoes-sentimentos",
        "titulo": "Emoções e sentimentos",
        "descricao": "Como expressar como você se sente.",
        "palavras": [
            ("嬉しい", "うれしい", "ureshii", "Feliz / Contente", "adjetivo i", "とても嬉しいです。", "Estou muito feliz.", None),
            ("悲しい", "かなしい", "kanashii", "Triste", "adjetivo i", "悲しい話です。", "É uma história triste.", None),
            ("楽しい", "たのしい", "tanoshii", "Divertido / Prazeroso", "adjetivo i", "旅行は楽しかったです。", "A viagem foi divertida.", None),
            ("怖い", "こわい", "kowai", "Assustador / Com medo", "adjetivo i", "犬が怖いです。", "Tenho medo de cachorro.", None),
            ("寂しい", "さびしい", "sabishii", "Solitário", "adjetivo i", "一人で寂しいです。", "Sozinho fico solitário.", None),
            ("恥ずかしい", "はずかしい", "hazukashii", "Envergonhado", "adjetivo i", "恥ずかしい話です。", "É uma história embaraçosa.", None),
            ("驚く", "おどろく", "odoroku", "Surpreender-se", "verbo (u)", "ニュースに驚きました。", "Fiquei surpreso com a notícia.", None),
            ("怒る", "おこる", "okoru", "Ficar bravo", "verbo (u)", "母が怒りました。", "Minha mãe ficou brava.", None),
            ("泣く", "なく", "naku", "Chorar", "verbo (u)", "子供が泣いています。", "A criança está chorando.", None),
            ("笑う", "わらう", "warau", "Rir / Sorrir", "verbo (u)", "みんなが笑いました。", "Todos riram.", None),
            ("心配", "しんぱい", "shinpai", "Preocupação", "substantivo / na", "心配しないでください。", "Não se preocupe.", None),
            ("安心", "あんしん", "anshin", "Alívio / Tranquilidade", "substantivo / na", "安心しました。", "Fiquei aliviado.", None),
        ],
    },
    {
        "slug": "verbos-te-form",
        "titulo": "Verbos úteis para a forma -te",
        "descricao": "Verbos comuns que aparecem em estruturas como ~ている, ~てください, ~てもいい.",
        "palavras": [
            ("待つ", "まつ", "matsu", "Esperar", "verbo (u)", "ちょっと待ってください。", "Espere um pouco, por favor.", None),
            ("作る", "つくる", "tsukuru", "Fazer / Criar", "verbo (u)", "料理を作ります。", "Vou cozinhar.", None),
            ("貸す", "かす", "kasu", "Emprestar (a alguém)", "verbo (u)", "本を貸してください。", "Empreste-me o livro.", None),
            ("借りる", "かりる", "kariru", "Pegar emprestado", "verbo (ru)", "本を借りました。", "Peguei um livro emprestado.", None),
            ("返す", "かえす", "kaesu", "Devolver", "verbo (u)", "明日返します。", "Devolvo amanhã.", None),
            ("教える", "おしえる", "oshieru", "Ensinar / Avisar", "verbo (ru)", "日本語を教えてください。", "Por favor, me ensine japonês.", None),
            ("習う", "ならう", "narau", "Aprender (com alguém)", "verbo (u)", "ピアノを習います。", "Vou aprender piano.", None),
            ("覚える", "おぼえる", "oboeru", "Memorizar / Lembrar", "verbo (ru)", "漢字を覚えます。", "Vou memorizar os kanjis.", None),
            ("忘れる", "わすれる", "wasureru", "Esquecer", "verbo (ru)", "傘を忘れました。", "Esqueci o guarda-chuva.", None),
            ("使う", "つかう", "tsukau", "Usar", "verbo (u)", "辞書を使います。", "Vou usar o dicionário.", None),
            ("洗う", "あらう", "arau", "Lavar", "verbo (u)", "手を洗ってください。", "Lave as mãos, por favor.", None),
            ("座る", "すわる", "suwaru", "Sentar", "verbo (u)", "椅子に座ってください。", "Sente-se na cadeira, por favor.", None),
        ],
    },
    {
        "slug": "compras-dinheiro",
        "titulo": "Compras e dinheiro",
        "descricao": "Do supermercado ao banco.",
        "palavras": [
            ("お金", "おかね", "okane", "Dinheiro", "substantivo", "お金がありません。", "Não tenho dinheiro.", None),
            ("値段", "ねだん", "nedan", "Preço", "substantivo", "値段はいくらですか。", "Qual é o preço?", None),
            ("高い", "たかい", "takai", "Caro / Alto", "adjetivo i", "値段が高いです。", "O preço é caro.", None),
            ("安い", "やすい", "yasui", "Barato", "adjetivo i", "ここは安いです。", "Aqui é barato.", None),
            ("買い物", "かいもの", "kaimono", "Compras", "substantivo", "買い物に行きます。", "Vou fazer compras.", None),
            ("売る", "うる", "uru", "Vender", "verbo (u)", "車を売りました。", "Vendi o carro.", None),
            ("払う", "はらう", "harau", "Pagar", "verbo (u)", "現金で払います。", "Vou pagar em dinheiro.", None),
            ("レジ", "レジ", "reji", "Caixa (registradora)", "substantivo", "レジで払ってください。", "Pague no caixa.", None),
            ("お釣り", "おつり", "otsuri", "Troco", "substantivo", "お釣りはいりません。", "Pode ficar com o troco.", None),
            ("カード", "カード", "kaado", "Cartão", "substantivo", "カードで払います。", "Vou pagar no cartão.", None),
            ("現金", "げんきん", "genkin", "Dinheiro vivo", "substantivo", "現金で払います。", "Vou pagar em dinheiro.", None),
            ("スーパー", "スーパー", "suupaa", "Supermercado", "substantivo", "スーパーで買います。", "Vou comprar no supermercado.", "Contração de スーパーマーケット."),
        ],
    },
]
